server.port=8083
spring.application.name=finance-service
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/erp_finance_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:inventory_user}
spring.datasource.password=${DB_PASSWORD:inventory123}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP:finance-service}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.listener.ack-mode=record
application.security.jwt.secret-key=${APPLICATION_SECURITY_JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
application.kafka.topics.stock-reserved=${STOCK_RESERVED_TOPIC:stock-reserved-topic}
application.kafka.topics.order-status-changed=${ORDER_STATUS_CHANGED_TOPIC:order-status-changed-topic}
finance.tax-rate=${FINANCE_TAX_RATE:0.18}
logging.level.com.finance=INFO
