server.port=${SERVER_PORT:8082}
spring.application.name=inventory-service
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/erp_inventory_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:inventory_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:inventory123}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.cache.type=redis
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=inventory-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
logging.level.org.springframework.kafka=${LOG_LEVEL_KAFKA:INFO}
logging.level.org.springframework.data.redis=${LOG_LEVEL_REDIS:INFO}
logging.level.com.inventory.inventory_service=${LOG_LEVEL_APP:INFO}
application.kafka.topics.order-placed=order-placed-topic
application.kafka.topics.stock-reserved=stock-reserved-topic
application.kafka.topics.stock-rejected=stock-rejected-topic
application.kafka.topics.stock-low=stock-low-topic
spring.jpa.open-in-view=false
spring.data.redis.repositories.enabled=false
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR
